//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIP_Report.WebService_SMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService_SMS.WebService_SMSSoap")]
    public interface WebService_SMSSoap {
        
        // CODEGEN: Generating message contract since message part namespace (http://SMS.SMSOutputSchema) does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_SMS/SMSRequestResponsePort", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="InsertSMSInfo")]
        WIP_Report.WebService_SMS.SMSRequestResponsePortResponse SMSRequestResponsePort(WIP_Report.WebService_SMS.SMSRequestResponsePortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_SMS/SMSRequestResponsePort", ReplyAction="*")]
        System.Threading.Tasks.Task<WIP_Report.WebService_SMS.SMSRequestResponsePortResponse> SMSRequestResponsePortAsync(WIP_Report.WebService_SMS.SMSRequestResponsePortRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://SMS.SMSInputSchema")]
    public partial class SMSInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private string mobile_NumberField;
        
        private string flagField;
        
        private string received_FromField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Mobile_Number {
            get {
                return this.mobile_NumberField;
            }
            set {
                this.mobile_NumberField = value;
                this.RaisePropertyChanged("Mobile_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Received_From {
            get {
                return this.received_FromField;
            }
            set {
                this.received_FromField = value;
                this.RaisePropertyChanged("Received_From");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://SMS.SMSOutputSchema")]
    public partial class InsertSMSInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InsertSMSInfoInsertStatus insertStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public InsertSMSInfoInsertStatus InsertStatus {
            get {
                return this.insertStatusField;
            }
            set {
                this.insertStatusField = value;
                this.RaisePropertyChanged("InsertStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://SMS.SMSOutputSchema")]
    public partial class InsertSMSInfoInsertStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SMSRequestResponsePort", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SMSRequestResponsePortRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SMS.SMSInputSchema", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://SMS.SMSInputSchema")]
        public WIP_Report.WebService_SMS.SMSInput SMSInput;
        
        public SMSRequestResponsePortRequest() {
        }
        
        public SMSRequestResponsePortRequest(WIP_Report.WebService_SMS.SMSInput SMSInput) {
            this.SMSInput = SMSInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SMSRequestResponsePortResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SMSRequestResponsePortResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SMS.SMSOutputSchema", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://SMS.SMSOutputSchema")]
        public WIP_Report.WebService_SMS.InsertSMSInfo InsertSMSInfo;
        
        public SMSRequestResponsePortResponse() {
        }
        
        public SMSRequestResponsePortResponse(WIP_Report.WebService_SMS.InsertSMSInfo InsertSMSInfo) {
            this.InsertSMSInfo = InsertSMSInfo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_SMSSoapChannel : WIP_Report.WebService_SMS.WebService_SMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_SMSSoapClient : System.ServiceModel.ClientBase<WIP_Report.WebService_SMS.WebService_SMSSoap>, WIP_Report.WebService_SMS.WebService_SMSSoap {
        
        public WebService_SMSSoapClient() {
        }
        
        public WebService_SMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_SMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_SMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_SMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WIP_Report.WebService_SMS.SMSRequestResponsePortResponse WIP_Report.WebService_SMS.WebService_SMSSoap.SMSRequestResponsePort(WIP_Report.WebService_SMS.SMSRequestResponsePortRequest request) {
            return base.Channel.SMSRequestResponsePort(request);
        }
        
        public WIP_Report.WebService_SMS.InsertSMSInfo SMSRequestResponsePort(WIP_Report.WebService_SMS.SMSInput SMSInput) {
            WIP_Report.WebService_SMS.SMSRequestResponsePortRequest inValue = new WIP_Report.WebService_SMS.SMSRequestResponsePortRequest();
            inValue.SMSInput = SMSInput;
            WIP_Report.WebService_SMS.SMSRequestResponsePortResponse retVal = ((WIP_Report.WebService_SMS.WebService_SMSSoap)(this)).SMSRequestResponsePort(inValue);
            return retVal.InsertSMSInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WIP_Report.WebService_SMS.SMSRequestResponsePortResponse> WIP_Report.WebService_SMS.WebService_SMSSoap.SMSRequestResponsePortAsync(WIP_Report.WebService_SMS.SMSRequestResponsePortRequest request) {
            return base.Channel.SMSRequestResponsePortAsync(request);
        }
        
        public System.Threading.Tasks.Task<WIP_Report.WebService_SMS.SMSRequestResponsePortResponse> SMSRequestResponsePortAsync(WIP_Report.WebService_SMS.SMSInput SMSInput) {
            WIP_Report.WebService_SMS.SMSRequestResponsePortRequest inValue = new WIP_Report.WebService_SMS.SMSRequestResponsePortRequest();
            inValue.SMSInput = SMSInput;
            return ((WIP_Report.WebService_SMS.WebService_SMSSoap)(this)).SMSRequestResponsePortAsync(inValue);
        }
    }
}
