//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIP_Report.CP_PersonalClientModi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CRM_LAIntegration/", ConfigurationName="CP_PersonalClientModi.CRM_LAIntegration_PersonalClientModify_PersonalClientModify" +
        "ReqResPort")]
    public interface CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPort {
        
        // CODEGEN: Generating message contract since the operation Operation_1 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Operation_1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WIP_Report.CP_PersonalClientModi.Operation_1Response Operation_1(WIP_Report.CP_PersonalClientModi.Operation_1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Operation_1", ReplyAction="*")]
        System.Threading.Tasks.Task<WIP_Report.CP_PersonalClientModi.Operation_1Response> Operation_1Async(WIP_Report.CP_PersonalClientModi.Operation_1Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CRM_LAIntegration.InputSchemaforPersonalClientModify")]
    public partial class PersonalClientModifyDynamicCase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CRM_LAIntegration.OutputSchemaforPersonalClientModify")]
    public partial class PersonalClientModifyDynamicCase1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Operation_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CRM_LAIntegration.InputSchemaforPersonalClientModify", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DynamicCase", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WIP_Report.CP_PersonalClientModi.PersonalClientModifyDynamicCase[] PersonalClientModify;
        
        public Operation_1Request() {
        }
        
        public Operation_1Request(WIP_Report.CP_PersonalClientModi.PersonalClientModifyDynamicCase[] PersonalClientModify) {
            this.PersonalClientModify = PersonalClientModify;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Operation_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CRM_LAIntegration.OutputSchemaforPersonalClientModify", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DynamicCase", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WIP_Report.CP_PersonalClientModi.PersonalClientModifyDynamicCase1[] PersonalClientModify;
        
        public Operation_1Response() {
        }
        
        public Operation_1Response(WIP_Report.CP_PersonalClientModi.PersonalClientModifyDynamicCase1[] PersonalClientModify) {
            this.PersonalClientModify = PersonalClientModify;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPortChannel : WIP_Report.CP_PersonalClientModi.CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPortClient : System.ServiceModel.ClientBase<WIP_Report.CP_PersonalClientModi.CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPort>, WIP_Report.CP_PersonalClientModi.CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPort {
        
        public CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPortClient() {
        }
        
        public CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WIP_Report.CP_PersonalClientModi.Operation_1Response WIP_Report.CP_PersonalClientModi.CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPort.Operation_1(WIP_Report.CP_PersonalClientModi.Operation_1Request request) {
            return base.Channel.Operation_1(request);
        }
        
        public WIP_Report.CP_PersonalClientModi.PersonalClientModifyDynamicCase1[] Operation_1(WIP_Report.CP_PersonalClientModi.PersonalClientModifyDynamicCase[] PersonalClientModify) {
            WIP_Report.CP_PersonalClientModi.Operation_1Request inValue = new WIP_Report.CP_PersonalClientModi.Operation_1Request();
            inValue.PersonalClientModify = PersonalClientModify;
            WIP_Report.CP_PersonalClientModi.Operation_1Response retVal = ((WIP_Report.CP_PersonalClientModi.CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPort)(this)).Operation_1(inValue);
            return retVal.PersonalClientModify;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WIP_Report.CP_PersonalClientModi.Operation_1Response> WIP_Report.CP_PersonalClientModi.CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPort.Operation_1Async(WIP_Report.CP_PersonalClientModi.Operation_1Request request) {
            return base.Channel.Operation_1Async(request);
        }
        
        public System.Threading.Tasks.Task<WIP_Report.CP_PersonalClientModi.Operation_1Response> Operation_1Async(WIP_Report.CP_PersonalClientModi.PersonalClientModifyDynamicCase[] PersonalClientModify) {
            WIP_Report.CP_PersonalClientModi.Operation_1Request inValue = new WIP_Report.CP_PersonalClientModi.Operation_1Request();
            inValue.PersonalClientModify = PersonalClientModify;
            return ((WIP_Report.CP_PersonalClientModi.CRM_LAIntegration_PersonalClientModify_PersonalClientModifyReqResPort)(this)).Operation_1Async(inValue);
        }
    }
}
