//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WIP_Report.PremiumRecieptNew {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ITwoWayAsyncVoid", Namespace="http://tempuri.org/")]
    public partial class BizTalkServiceInstance : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PremiumPaymentRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BizTalkServiceInstance() {
            this.Url = global::WIP_Report.Properties.Settings.Default.WIP_Report_PremiumRecieptNew_BizTalkServiceInstance;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PremiumPaymentRequestCompletedEventHandler PremiumPaymentRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("PremiumPaymentRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void PremiumPaymentRequest([System.Xml.Serialization.XmlElementAttribute(Namespace="http://PortalDay2.InputSchemafromPortal")] PortalInput PortalInput) {
            this.Invoke("PremiumPaymentRequest", new object[] {
                        PortalInput});
        }
        
        /// <remarks/>
        public void PremiumPaymentRequestAsync(PortalInput PortalInput) {
            this.PremiumPaymentRequestAsync(PortalInput, null);
        }
        
        /// <remarks/>
        public void PremiumPaymentRequestAsync(PortalInput PortalInput, object userState) {
            if ((this.PremiumPaymentRequestOperationCompleted == null)) {
                this.PremiumPaymentRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPremiumPaymentRequestOperationCompleted);
            }
            this.InvokeAsync("PremiumPaymentRequest", new object[] {
                        PortalInput}, this.PremiumPaymentRequestOperationCompleted, userState);
        }
        
        private void OnPremiumPaymentRequestOperationCompleted(object arg) {
            if ((this.PremiumPaymentRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PremiumPaymentRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PortalDay2.InputSchemafromPortal")]
    public partial class PortalInput {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PremiumPaymentInput", typeof(PremiumPaymentInput), Namespace="http://BOsTesting.PortalInputSchemaforPremiumPayment")]
        [System.Xml.Serialization.XmlElementAttribute("ReinstatementAmount", typeof(ReinstatementAmount), Namespace="http://BOsTesting.PortalInputSchemaforReinstatementAmount")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BOsTesting.PortalInputSchemaforPremiumPayment")]
    public partial class PremiumPaymentInput {
        
        private string transactionIdField;
        
        private string policyNumberField;
        
        private string premiumAmountField;
        
        private string paymentGatewayResultField;
        
        private string premiumPaymentFlagField;
        
        private string payTypeField;
        
        private string bGENSR289DESCRNField;
        
        private string bGENS2610AGNTSELField;
        
        private string bGENS2610REALDATEField;
        
        private string bGENS2610REALFLAGField;
        
        private string bGENS2610REALTIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PremiumAmount {
            get {
                return this.premiumAmountField;
            }
            set {
                this.premiumAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string PaymentGatewayResult {
            get {
                return this.paymentGatewayResultField;
            }
            set {
                this.paymentGatewayResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PremiumPaymentFlag {
            get {
                return this.premiumPaymentFlagField;
            }
            set {
                this.premiumPaymentFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PayType {
            get {
                return this.payTypeField;
            }
            set {
                this.payTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BGEN-SR289-DESCRN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BGENSR289DESCRN {
            get {
                return this.bGENSR289DESCRNField;
            }
            set {
                this.bGENSR289DESCRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BGEN-S2610-AGNTSEL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BGENS2610AGNTSEL {
            get {
                return this.bGENS2610AGNTSELField;
            }
            set {
                this.bGENS2610AGNTSELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BGEN-S2610-REALDATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BGENS2610REALDATE {
            get {
                return this.bGENS2610REALDATEField;
            }
            set {
                this.bGENS2610REALDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BGEN-S2610-REALFLAG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BGENS2610REALFLAG {
            get {
                return this.bGENS2610REALFLAGField;
            }
            set {
                this.bGENS2610REALFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BGEN-S2610-REALTIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BGENS2610REALTIME {
            get {
                return this.bGENS2610REALTIMEField;
            }
            set {
                this.bGENS2610REALTIMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BOsTesting.PortalInputSchemaforReinstatementAmount")]
    public partial class ReinstatementAmount {
        
        private string transactionIdField;
        
        private string contractNumberField;
        
        private string reinstatementAmountFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReinstatementAmountFlag {
            get {
                return this.reinstatementAmountFlagField;
            }
            set {
                this.reinstatementAmountFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PremiumPaymentRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591