//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIP_Report.CRMCallUpdation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRMCallUpdation.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SUDCallUpdation", ReplyAction="*")]
        WIP_Report.CRMCallUpdation.SUDCallUpdationResponse SUDCallUpdation(WIP_Report.CRMCallUpdation.SUDCallUpdationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SUDCallUpdation", ReplyAction="*")]
        System.Threading.Tasks.Task<WIP_Report.CRMCallUpdation.SUDCallUpdationResponse> SUDCallUpdationAsync(WIP_Report.CRMCallUpdation.SUDCallUpdationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SUDCallUpdationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SUDCallUpdation", Namespace="http://tempuri.org/", Order=0)]
        public WIP_Report.CRMCallUpdation.SUDCallUpdationRequestBody Body;
        
        public SUDCallUpdationRequest() {
        }
        
        public SUDCallUpdationRequest(WIP_Report.CRMCallUpdation.SUDCallUpdationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SUDCallUpdationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xml;
        
        public SUDCallUpdationRequestBody() {
        }
        
        public SUDCallUpdationRequestBody(System.Xml.Linq.XElement xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SUDCallUpdationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SUDCallUpdationResponse", Namespace="http://tempuri.org/", Order=0)]
        public WIP_Report.CRMCallUpdation.SUDCallUpdationResponseBody Body;
        
        public SUDCallUpdationResponse() {
        }
        
        public SUDCallUpdationResponse(WIP_Report.CRMCallUpdation.SUDCallUpdationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SUDCallUpdationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SUDCallUpdationResult;
        
        public SUDCallUpdationResponseBody() {
        }
        
        public SUDCallUpdationResponseBody(System.Xml.Linq.XElement SUDCallUpdationResult) {
            this.SUDCallUpdationResult = SUDCallUpdationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WIP_Report.CRMCallUpdation.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WIP_Report.CRMCallUpdation.Service1Soap>, WIP_Report.CRMCallUpdation.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WIP_Report.CRMCallUpdation.SUDCallUpdationResponse WIP_Report.CRMCallUpdation.Service1Soap.SUDCallUpdation(WIP_Report.CRMCallUpdation.SUDCallUpdationRequest request) {
            return base.Channel.SUDCallUpdation(request);
        }
        
        public System.Xml.Linq.XElement SUDCallUpdation(System.Xml.Linq.XElement xml) {
            WIP_Report.CRMCallUpdation.SUDCallUpdationRequest inValue = new WIP_Report.CRMCallUpdation.SUDCallUpdationRequest();
            inValue.Body = new WIP_Report.CRMCallUpdation.SUDCallUpdationRequestBody();
            inValue.Body.xml = xml;
            WIP_Report.CRMCallUpdation.SUDCallUpdationResponse retVal = ((WIP_Report.CRMCallUpdation.Service1Soap)(this)).SUDCallUpdation(inValue);
            return retVal.Body.SUDCallUpdationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WIP_Report.CRMCallUpdation.SUDCallUpdationResponse> WIP_Report.CRMCallUpdation.Service1Soap.SUDCallUpdationAsync(WIP_Report.CRMCallUpdation.SUDCallUpdationRequest request) {
            return base.Channel.SUDCallUpdationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WIP_Report.CRMCallUpdation.SUDCallUpdationResponse> SUDCallUpdationAsync(System.Xml.Linq.XElement xml) {
            WIP_Report.CRMCallUpdation.SUDCallUpdationRequest inValue = new WIP_Report.CRMCallUpdation.SUDCallUpdationRequest();
            inValue.Body = new WIP_Report.CRMCallUpdation.SUDCallUpdationRequestBody();
            inValue.Body.xml = xml;
            return ((WIP_Report.CRMCallUpdation.Service1Soap)(this)).SUDCallUpdationAsync(inValue);
        }
    }
}
