//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIP_Report.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.8.253/SUD_FeedbackService/Feedback.svc")]
        public string WIP_Report_FeedbackWebservice_Feedback {
            get {
                return ((string)(this["WIP_Report_FeedbackWebservice_Feedback"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://DC-OMNIDEV-01:8080/WebserviceDocumentUpload_PS/WebservicemainService_DocUp" +
            "load")]
        public string WIP_Report_Omni_doc_upload_WebservicemainService_DocUpload {
            get {
                return ((string)(this["WIP_Report_Omni_doc_upload_WebservicemainService_DocUpload"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.20.151/GetallPolicyDetailsInformation_BankPortal/WebService_GetallPol" +
            "icydetails.asmx")]
        public string WIP_Report_GetLoginUser_PolicyDetails_WebService_GetallPolicydetails {
            get {
                return ((string)(this["WIP_Report_GetLoginUser_PolicyDetails_WebService_GetallPolicydetails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.20.150/SendMail2User_WebService/SendMail2User_Service.asmx")]
        public string WIP_Report_SendingMailSoapClientNew_SendMail2User_Service {
            get {
                return ((string)(this["WIP_Report_SendingMailSoapClientNew_SendMail2User_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dc-biztlkpr-01.sud.in/BOsTesting/BOsTesting_Orchestration_1_PremiumPayment" +
            "Request.svc")]
        public string WIP_Report_PremiumRecieptNew_BizTalkServiceInstance {
            get {
                return ((string)(this["WIP_Report_PremiumRecieptNew_BizTalkServiceInstance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dc-biztlkpr-01.sud.in/BOsTesting/BOsTesting_Reinstatement_ReinstatementPor" +
            "t.svc")]
        public string WIP_Report_ReinstatementReciept_BizTalkServiceInstance {
            get {
                return ((string)(this["WIP_Report_ReinstatementReciept_BizTalkServiceInstance"]));
            }
        }
    }
}
