//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIP_Report.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService_GetallPolicydetailsSoap")]
    public interface WebService_GetallPolicydetailsSoap {
        
        // CODEGEN: Generating message contract since message part namespace (http://GetAllPolicyDetailsOutput) does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_GetallPolicydetails/Operation_1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RetriveServiceOutput")]
        WIP_Report.ServiceReference1.Operation_1Response Operation_1(WIP_Report.ServiceReference1.Operation_1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebService_GetallPolicydetails/Operation_1", ReplyAction="*")]
        System.Threading.Tasks.Task<WIP_Report.ServiceReference1.Operation_1Response> Operation_1Async(WIP_Report.ServiceReference1.Operation_1Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://GetAllPolicyDetailsInput")]
    public partial class RetriveServiceInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Logininput", typeof(Logininput), Namespace="http://Daiichi.Login", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MyAddressinput", typeof(MyAddressinput), Namespace="http://Daiichi.MyAddress", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MyAgent", typeof(MyAgent), Namespace="http://Daiichi.MyAgent", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MyFund", typeof(MyFund), Namespace="http://Daiichi.MyFund", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MyPolicy", typeof(MyPolicy), Namespace="http://Daiichi.MyPolicy", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PolicyPayoutDetails", typeof(PolicyPayoutDetails), Namespace="http://Daiichi.PolicyPayoutdetailsinput", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RiderDetails", typeof(RiderDetails), Namespace="http://Daiichi.RiderDetails", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MyNominee", typeof(MyNominee), Namespace="http://GetallPolicydetails.MyNomineeInput", Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.Login")]
    public partial class Logininput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIDField;
        
        private string getPolicyFundDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
                this.RaisePropertyChanged("ClientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string GetPolicyFundDetails {
            get {
                return this.getPolicyFundDetailsField;
            }
            set {
                this.getPolicyFundDetailsField = value;
                this.RaisePropertyChanged("GetPolicyFundDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.MyAddress")]
    public partial class MyAddressinput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIDField;
        
        private string getClientDetailsField;
        
        private string policy_NumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
                this.RaisePropertyChanged("ClientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string GetClientDetails {
            get {
                return this.getClientDetailsField;
            }
            set {
                this.getClientDetailsField = value;
                this.RaisePropertyChanged("GetClientDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string Policy_Number {
            get {
                return this.policy_NumberField;
            }
            set {
                this.policy_NumberField = value;
                this.RaisePropertyChanged("Policy_Number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.MyAgent")]
    public partial class MyAgent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIDField;
        
        private string getAgentDetailsField;
        
        private string policyNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
                this.RaisePropertyChanged("ClientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string GetAgentDetails {
            get {
                return this.getAgentDetailsField;
            }
            set {
                this.getAgentDetailsField = value;
                this.RaisePropertyChanged("GetAgentDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
                this.RaisePropertyChanged("PolicyNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.MyFund")]
    public partial class MyFund : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string policyNumberField;
        
        private string myFundDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
                this.RaisePropertyChanged("PolicyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MyFundDetails {
            get {
                return this.myFundDetailsField;
            }
            set {
                this.myFundDetailsField = value;
                this.RaisePropertyChanged("MyFundDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.MyPolicy")]
    public partial class MyPolicy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIDField;
        
        private string getPolicyDetailsField;
        
        private string policy_NumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
                this.RaisePropertyChanged("ClientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string GetPolicyDetails {
            get {
                return this.getPolicyDetailsField;
            }
            set {
                this.getPolicyDetailsField = value;
                this.RaisePropertyChanged("GetPolicyDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string Policy_Number {
            get {
                return this.policy_NumberField;
            }
            set {
                this.policy_NumberField = value;
                this.RaisePropertyChanged("Policy_Number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.PolicyPayoutdetailsinput")]
    public partial class PolicyPayoutDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIDField;
        
        private string getPayoutDetailsField;
        
        private string policy_NumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
                this.RaisePropertyChanged("ClientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string GetPayoutDetails {
            get {
                return this.getPayoutDetailsField;
            }
            set {
                this.getPayoutDetailsField = value;
                this.RaisePropertyChanged("GetPayoutDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string Policy_Number {
            get {
                return this.policy_NumberField;
            }
            set {
                this.policy_NumberField = value;
                this.RaisePropertyChanged("Policy_Number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.RiderDetails")]
    public partial class RiderDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIDField;
        
        private string getRiderDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
                this.RaisePropertyChanged("ClientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string GetRiderDetails {
            get {
                return this.getRiderDetailsField;
            }
            set {
                this.getRiderDetailsField = value;
                this.RaisePropertyChanged("GetRiderDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://GetallPolicydetails.MyNomineeInput")]
    public partial class MyNominee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIdField;
        
        private string policyNumberField;
        
        private string getNomineeDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
                this.RaisePropertyChanged("PolicyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string GetNomineeDetails {
            get {
                return this.getNomineeDetailsField;
            }
            set {
                this.getNomineeDetailsField = value;
                this.RaisePropertyChanged("GetNomineeDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://GetAllPolicyDetailsOutput")]
    public partial class RetriveServiceOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fault", typeof(Fault), Namespace="http://Daiichi.Fault", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LoginOutput", typeof(LoginOutput), Namespace="http://Daiichi.LoginOutput", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MyAddressOutput", typeof(MyAddressOutput), Namespace="http://Daiichi.MyAddressOutput", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MyAgentOutput", typeof(MyAgentOutput), Namespace="http://Daiichi.MyAgentOutput", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MyFundOutput", typeof(MyFundOutput), Namespace="http://Daiichi.MyFundOutput", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MyPolicyOutput", typeof(MyPolicyOutput), Namespace="http://Daiichi.MyPolicyOutput", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PolicyPayoutdetailsOutput", typeof(PolicyPayoutdetailsOutput), Namespace="http://Daiichi.PolicyPayoutdetailsoutput", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RiderDetailsOutput", typeof(RiderDetailsOutput), Namespace="http://Daiichi.RiderDetailsOutput", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MyNomineeOutput", typeof(MyNomineeOutput), Namespace="http://GetallPolicydetails.MyNomineeOutput", Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.Fault")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errormsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Errormsg {
            get {
                return this.errormsgField;
            }
            set {
                this.errormsgField = value;
                this.RaisePropertyChanged("Errormsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.LoginOutput")]
    public partial class LoginOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string policyNumberField;
        
        private string policyHolderNameField;
        
        private string premiumAmountField;
        
        private string sumAssuredField;
        
        private string productNameField;
        
        private string policyTermField;
        
        private string nextPremiumDueDateField;
        
        private string lastPremiumpaiddateField;
        
        private string policyCommencementDateField;
        
        private string policyStatusField;
        
        private string dateofMaturityField;
        
        private string policyProductCodeField;
        
        private string policyProductCategoryField;
        
        private string totalPolicyValueField;
        
        private string fundNameField;
        
        private string nAVField;
        
        private string numberofunitsField;
        
        private string fundvalueField;
        
        private string currentapportionmentField;
        
        private string existing_ModeField;
        
        private string premium_Cess_TermField;
        
        private string fund_Short_NameField;
        
        private string client_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
                this.RaisePropertyChanged("PolicyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string PolicyHolderName {
            get {
                return this.policyHolderNameField;
            }
            set {
                this.policyHolderNameField = value;
                this.RaisePropertyChanged("PolicyHolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string PremiumAmount {
            get {
                return this.premiumAmountField;
            }
            set {
                this.premiumAmountField = value;
                this.RaisePropertyChanged("PremiumAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string SumAssured {
            get {
                return this.sumAssuredField;
            }
            set {
                this.sumAssuredField = value;
                this.RaisePropertyChanged("SumAssured");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string PolicyTerm {
            get {
                return this.policyTermField;
            }
            set {
                this.policyTermField = value;
                this.RaisePropertyChanged("PolicyTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string NextPremiumDueDate {
            get {
                return this.nextPremiumDueDateField;
            }
            set {
                this.nextPremiumDueDateField = value;
                this.RaisePropertyChanged("NextPremiumDueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string LastPremiumpaiddate {
            get {
                return this.lastPremiumpaiddateField;
            }
            set {
                this.lastPremiumpaiddateField = value;
                this.RaisePropertyChanged("LastPremiumpaiddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string PolicyCommencementDate {
            get {
                return this.policyCommencementDateField;
            }
            set {
                this.policyCommencementDateField = value;
                this.RaisePropertyChanged("PolicyCommencementDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string PolicyStatus {
            get {
                return this.policyStatusField;
            }
            set {
                this.policyStatusField = value;
                this.RaisePropertyChanged("PolicyStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string DateofMaturity {
            get {
                return this.dateofMaturityField;
            }
            set {
                this.dateofMaturityField = value;
                this.RaisePropertyChanged("DateofMaturity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string PolicyProductCode {
            get {
                return this.policyProductCodeField;
            }
            set {
                this.policyProductCodeField = value;
                this.RaisePropertyChanged("PolicyProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string PolicyProductCategory {
            get {
                return this.policyProductCategoryField;
            }
            set {
                this.policyProductCategoryField = value;
                this.RaisePropertyChanged("PolicyProductCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string TotalPolicyValue {
            get {
                return this.totalPolicyValueField;
            }
            set {
                this.totalPolicyValueField = value;
                this.RaisePropertyChanged("TotalPolicyValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string FundName {
            get {
                return this.fundNameField;
            }
            set {
                this.fundNameField = value;
                this.RaisePropertyChanged("FundName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string NAV {
            get {
                return this.nAVField;
            }
            set {
                this.nAVField = value;
                this.RaisePropertyChanged("NAV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string Numberofunits {
            get {
                return this.numberofunitsField;
            }
            set {
                this.numberofunitsField = value;
                this.RaisePropertyChanged("Numberofunits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string Fundvalue {
            get {
                return this.fundvalueField;
            }
            set {
                this.fundvalueField = value;
                this.RaisePropertyChanged("Fundvalue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string Currentapportionment {
            get {
                return this.currentapportionmentField;
            }
            set {
                this.currentapportionmentField = value;
                this.RaisePropertyChanged("Currentapportionment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public string Existing_Mode {
            get {
                return this.existing_ModeField;
            }
            set {
                this.existing_ModeField = value;
                this.RaisePropertyChanged("Existing_Mode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public string Premium_Cess_Term {
            get {
                return this.premium_Cess_TermField;
            }
            set {
                this.premium_Cess_TermField = value;
                this.RaisePropertyChanged("Premium_Cess_Term");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Fund_Short_Name {
            get {
                return this.fund_Short_NameField;
            }
            set {
                this.fund_Short_NameField = value;
                this.RaisePropertyChanged("Fund_Short_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Client_ID {
            get {
                return this.client_IDField;
            }
            set {
                this.client_IDField = value;
                this.RaisePropertyChanged("Client_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.MyAddressOutput")]
    public partial class MyAddressOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string salutationField;
        
        private string customerNameField;
        
        private string dOBField;
        
        private string genderField;
        
        private string streetField;
        
        private string line1Field;
        
        private string line2Field;
        
        private string line3Field;
        
        private string stateField;
        
        private string cityField;
        
        private string pINField;
        
        private string countryField;
        
        private string businessField;
        
        private string mailidField;
        
        private string phone1Field;
        
        private string phone2Field;
        
        private string mobileNoField;
        
        private string marital_StatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
                this.RaisePropertyChanged("Salutation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
                this.RaisePropertyChanged("DOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
                this.RaisePropertyChanged("Line1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
                this.RaisePropertyChanged("Line2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string Line3 {
            get {
                return this.line3Field;
            }
            set {
                this.line3Field = value;
                this.RaisePropertyChanged("Line3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string PIN {
            get {
                return this.pINField;
            }
            set {
                this.pINField = value;
                this.RaisePropertyChanged("PIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string Business {
            get {
                return this.businessField;
            }
            set {
                this.businessField = value;
                this.RaisePropertyChanged("Business");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string Mailid {
            get {
                return this.mailidField;
            }
            set {
                this.mailidField = value;
                this.RaisePropertyChanged("Mailid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string Phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
                this.RaisePropertyChanged("Phone1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string Phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
                this.RaisePropertyChanged("Phone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string MobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
                this.RaisePropertyChanged("MobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string Marital_Status {
            get {
                return this.marital_StatusField;
            }
            set {
                this.marital_StatusField = value;
                this.RaisePropertyChanged("Marital_Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.MyAgentOutput")]
    public partial class MyAgentOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string policyNumberField;
        
        private string customer_NameField;
        
        private string phone1Field;
        
        private string phone2Field;
        
        private string mobile_NoField;
        
        private string mail_IdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
                this.RaisePropertyChanged("PolicyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Customer_Name {
            get {
                return this.customer_NameField;
            }
            set {
                this.customer_NameField = value;
                this.RaisePropertyChanged("Customer_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string Phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
                this.RaisePropertyChanged("Phone1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string Phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
                this.RaisePropertyChanged("Phone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string Mobile_No {
            get {
                return this.mobile_NoField;
            }
            set {
                this.mobile_NoField = value;
                this.RaisePropertyChanged("Mobile_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string Mail_Id {
            get {
                return this.mail_IdField;
            }
            set {
                this.mail_IdField = value;
                this.RaisePropertyChanged("Mail_Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.MyFundOutput")]
    public partial class MyFundOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fundNameField;
        
        private string nAVField;
        
        private string numberofunitsField;
        
        private string fundvalueField;
        
        private string currentapportionmentField;
        
        private string fund_Short_NameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string FundName {
            get {
                return this.fundNameField;
            }
            set {
                this.fundNameField = value;
                this.RaisePropertyChanged("FundName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string NAV {
            get {
                return this.nAVField;
            }
            set {
                this.nAVField = value;
                this.RaisePropertyChanged("NAV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string Numberofunits {
            get {
                return this.numberofunitsField;
            }
            set {
                this.numberofunitsField = value;
                this.RaisePropertyChanged("Numberofunits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string Fundvalue {
            get {
                return this.fundvalueField;
            }
            set {
                this.fundvalueField = value;
                this.RaisePropertyChanged("Fundvalue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string Currentapportionment {
            get {
                return this.currentapportionmentField;
            }
            set {
                this.currentapportionmentField = value;
                this.RaisePropertyChanged("Currentapportionment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Fund_Short_Name {
            get {
                return this.fund_Short_NameField;
            }
            set {
                this.fund_Short_NameField = value;
                this.RaisePropertyChanged("Fund_Short_Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.MyPolicyOutput")]
    public partial class MyPolicyOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string policyNumberField;
        
        private string policyHolderNameField;
        
        private string premiumAmountField;
        
        private string sumAssuredField;
        
        private string productNameField;
        
        private string policyTermField;
        
        private string nextPremiumDueDateField;
        
        private string lastPremiumpaiddateField;
        
        private string policyCommencementDateField;
        
        private string policyStatusField;
        
        private string dateofMaturityField;
        
        private string policyProductCodeField;
        
        private string policyProductCategoryField;
        
        private string totalPolicyValueField;
        
        private string existing_ModeField;
        
        private string premium_Cess_TermField;
        
        private string premium_StatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
                this.RaisePropertyChanged("PolicyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string PolicyHolderName {
            get {
                return this.policyHolderNameField;
            }
            set {
                this.policyHolderNameField = value;
                this.RaisePropertyChanged("PolicyHolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string PremiumAmount {
            get {
                return this.premiumAmountField;
            }
            set {
                this.premiumAmountField = value;
                this.RaisePropertyChanged("PremiumAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string SumAssured {
            get {
                return this.sumAssuredField;
            }
            set {
                this.sumAssuredField = value;
                this.RaisePropertyChanged("SumAssured");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string PolicyTerm {
            get {
                return this.policyTermField;
            }
            set {
                this.policyTermField = value;
                this.RaisePropertyChanged("PolicyTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string NextPremiumDueDate {
            get {
                return this.nextPremiumDueDateField;
            }
            set {
                this.nextPremiumDueDateField = value;
                this.RaisePropertyChanged("NextPremiumDueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string LastPremiumpaiddate {
            get {
                return this.lastPremiumpaiddateField;
            }
            set {
                this.lastPremiumpaiddateField = value;
                this.RaisePropertyChanged("LastPremiumpaiddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string PolicyCommencementDate {
            get {
                return this.policyCommencementDateField;
            }
            set {
                this.policyCommencementDateField = value;
                this.RaisePropertyChanged("PolicyCommencementDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string PolicyStatus {
            get {
                return this.policyStatusField;
            }
            set {
                this.policyStatusField = value;
                this.RaisePropertyChanged("PolicyStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string DateofMaturity {
            get {
                return this.dateofMaturityField;
            }
            set {
                this.dateofMaturityField = value;
                this.RaisePropertyChanged("DateofMaturity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string PolicyProductCode {
            get {
                return this.policyProductCodeField;
            }
            set {
                this.policyProductCodeField = value;
                this.RaisePropertyChanged("PolicyProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string PolicyProductCategory {
            get {
                return this.policyProductCategoryField;
            }
            set {
                this.policyProductCategoryField = value;
                this.RaisePropertyChanged("PolicyProductCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string TotalPolicyValue {
            get {
                return this.totalPolicyValueField;
            }
            set {
                this.totalPolicyValueField = value;
                this.RaisePropertyChanged("TotalPolicyValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string Existing_Mode {
            get {
                return this.existing_ModeField;
            }
            set {
                this.existing_ModeField = value;
                this.RaisePropertyChanged("Existing_Mode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string Premium_Cess_Term {
            get {
                return this.premium_Cess_TermField;
            }
            set {
                this.premium_Cess_TermField = value;
                this.RaisePropertyChanged("Premium_Cess_Term");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string Premium_Status {
            get {
                return this.premium_StatusField;
            }
            set {
                this.premium_StatusField = value;
                this.RaisePropertyChanged("Premium_Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.PolicyPayoutdetailsoutput")]
    public partial class PolicyPayoutdetailsOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string policyNumberField;
        
        private string policyLapseDateField;
        
        private string surrenderValueField;
        
        private string policyTermField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
                this.RaisePropertyChanged("PolicyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string PolicyLapseDate {
            get {
                return this.policyLapseDateField;
            }
            set {
                this.policyLapseDateField = value;
                this.RaisePropertyChanged("PolicyLapseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string SurrenderValue {
            get {
                return this.surrenderValueField;
            }
            set {
                this.surrenderValueField = value;
                this.RaisePropertyChanged("SurrenderValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string PolicyTerm {
            get {
                return this.policyTermField;
            }
            set {
                this.policyTermField = value;
                this.RaisePropertyChanged("PolicyTerm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Daiichi.RiderDetailsOutput")]
    public partial class RiderDetailsOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string existingModalPremiumField;
        
        private string premiumAmountField;
        
        private string policyNumberField;
        
        private string riderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ExistingModalPremium {
            get {
                return this.existingModalPremiumField;
            }
            set {
                this.existingModalPremiumField = value;
                this.RaisePropertyChanged("ExistingModalPremium");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string PremiumAmount {
            get {
                return this.premiumAmountField;
            }
            set {
                this.premiumAmountField = value;
                this.RaisePropertyChanged("PremiumAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
                this.RaisePropertyChanged("PolicyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string Rider {
            get {
                return this.riderField;
            }
            set {
                this.riderField = value;
                this.RaisePropertyChanged("Rider");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://GetallPolicydetails.MyNomineeOutput")]
    public partial class MyNomineeOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string policy_NumberField;
        
        private string client_IDField;
        
        private string customer_NameField;
        
        private string beneficiary_RelationshipField;
        
        private string dOBField;
        
        private string genderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Policy_Number {
            get {
                return this.policy_NumberField;
            }
            set {
                this.policy_NumberField = value;
                this.RaisePropertyChanged("Policy_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Client_ID {
            get {
                return this.client_IDField;
            }
            set {
                this.client_IDField = value;
                this.RaisePropertyChanged("Client_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string Customer_Name {
            get {
                return this.customer_NameField;
            }
            set {
                this.customer_NameField = value;
                this.RaisePropertyChanged("Customer_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string Beneficiary_Relationship {
            get {
                return this.beneficiary_RelationshipField;
            }
            set {
                this.beneficiary_RelationshipField = value;
                this.RaisePropertyChanged("Beneficiary_Relationship");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
                this.RaisePropertyChanged("DOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Operation_1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Operation_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://GetAllPolicyDetailsInput", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://GetAllPolicyDetailsInput")]
        public WIP_Report.ServiceReference1.RetriveServiceInput RetriveServiceInput;
        
        public Operation_1Request() {
        }
        
        public Operation_1Request(WIP_Report.ServiceReference1.RetriveServiceInput RetriveServiceInput) {
            this.RetriveServiceInput = RetriveServiceInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Operation_1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Operation_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://GetAllPolicyDetailsOutput", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://GetAllPolicyDetailsOutput")]
        public WIP_Report.ServiceReference1.RetriveServiceOutput RetriveServiceOutput;
        
        public Operation_1Response() {
        }
        
        public Operation_1Response(WIP_Report.ServiceReference1.RetriveServiceOutput RetriveServiceOutput) {
            this.RetriveServiceOutput = RetriveServiceOutput;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_GetallPolicydetailsSoapChannel : WIP_Report.ServiceReference1.WebService_GetallPolicydetailsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_GetallPolicydetailsSoapClient : System.ServiceModel.ClientBase<WIP_Report.ServiceReference1.WebService_GetallPolicydetailsSoap>, WIP_Report.ServiceReference1.WebService_GetallPolicydetailsSoap {
        
        public WebService_GetallPolicydetailsSoapClient() {
        }
        
        public WebService_GetallPolicydetailsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_GetallPolicydetailsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_GetallPolicydetailsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_GetallPolicydetailsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WIP_Report.ServiceReference1.Operation_1Response WIP_Report.ServiceReference1.WebService_GetallPolicydetailsSoap.Operation_1(WIP_Report.ServiceReference1.Operation_1Request request) {
            return base.Channel.Operation_1(request);
        }
        
        public WIP_Report.ServiceReference1.RetriveServiceOutput Operation_1(WIP_Report.ServiceReference1.RetriveServiceInput RetriveServiceInput) {
            WIP_Report.ServiceReference1.Operation_1Request inValue = new WIP_Report.ServiceReference1.Operation_1Request();
            inValue.RetriveServiceInput = RetriveServiceInput;
            WIP_Report.ServiceReference1.Operation_1Response retVal = ((WIP_Report.ServiceReference1.WebService_GetallPolicydetailsSoap)(this)).Operation_1(inValue);
            return retVal.RetriveServiceOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WIP_Report.ServiceReference1.Operation_1Response> WIP_Report.ServiceReference1.WebService_GetallPolicydetailsSoap.Operation_1Async(WIP_Report.ServiceReference1.Operation_1Request request) {
            return base.Channel.Operation_1Async(request);
        }
        
        public System.Threading.Tasks.Task<WIP_Report.ServiceReference1.Operation_1Response> Operation_1Async(WIP_Report.ServiceReference1.RetriveServiceInput RetriveServiceInput) {
            WIP_Report.ServiceReference1.Operation_1Request inValue = new WIP_Report.ServiceReference1.Operation_1Request();
            inValue.RetriveServiceInput = RetriveServiceInput;
            return ((WIP_Report.ServiceReference1.WebService_GetallPolicydetailsSoap)(this)).Operation_1Async(inValue);
        }
    }
}
