//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIP_Report.CRMCallCreation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grievance", Namespace="http://schemas.datacontract.org/2004/07/SUD.CRM.Portal")]
    [System.SerializableAttribute()]
    public partial class Grievance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChequeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ClaimAmountReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ClaimAmountRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ClaimIntimationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PanCardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PincodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RationCardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecieptNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesPersonCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SudRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeOfPortalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoterIdNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address3 {
            get {
                return this.Address3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address3Field, value) != true)) {
                    this.Address3Field = value;
                    this.RaisePropertyChanged("Address3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationNo {
            get {
                return this.ApplicationNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNoField, value) != true)) {
                    this.ApplicationNoField = value;
                    this.RaisePropertyChanged("ApplicationNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOC {
            get {
                return this.BOCField;
            }
            set {
                if ((object.ReferenceEquals(this.BOCField, value) != true)) {
                    this.BOCField = value;
                    this.RaisePropertyChanged("BOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bank {
            get {
                return this.BankField;
            }
            set {
                if ((object.ReferenceEquals(this.BankField, value) != true)) {
                    this.BankField = value;
                    this.RaisePropertyChanged("Bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallTypeId {
            get {
                return this.CallTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CallTypeIdField, value) != true)) {
                    this.CallTypeIdField = value;
                    this.RaisePropertyChanged("CallTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChequeNo {
            get {
                return this.ChequeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChequeNoField, value) != true)) {
                    this.ChequeNoField = value;
                    this.RaisePropertyChanged("ChequeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CityIdField, value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ClaimAmountReceived {
            get {
                return this.ClaimAmountReceivedField;
            }
            set {
                if ((this.ClaimAmountReceivedField.Equals(value) != true)) {
                    this.ClaimAmountReceivedField = value;
                    this.RaisePropertyChanged("ClaimAmountReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ClaimAmountRequested {
            get {
                return this.ClaimAmountRequestedField;
            }
            set {
                if ((this.ClaimAmountRequestedField.Equals(value) != true)) {
                    this.ClaimAmountRequestedField = value;
                    this.RaisePropertyChanged("ClaimAmountRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ClaimIntimationDate {
            get {
                return this.ClaimIntimationDateField;
            }
            set {
                if ((this.ClaimIntimationDateField.Equals(value) != true)) {
                    this.ClaimIntimationDateField = value;
                    this.RaisePropertyChanged("ClaimIntimationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimNo {
            get {
                return this.ClaimNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimNoField, value) != true)) {
                    this.ClaimNoField = value;
                    this.RaisePropertyChanged("ClaimNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictId {
            get {
                return this.DistrictIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictIdField, value) != true)) {
                    this.DistrictIdField = value;
                    this.RaisePropertyChanged("DistrictId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaxNo {
            get {
                return this.FaxNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNoField, value) != true)) {
                    this.FaxNoField = value;
                    this.RaisePropertyChanged("FaxNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginIdField, value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PanCardNo {
            get {
                return this.PanCardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PanCardNoField, value) != true)) {
                    this.PanCardNoField = value;
                    this.RaisePropertyChanged("PanCardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNo {
            get {
                return this.PassportNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportNoField, value) != true)) {
                    this.PassportNoField = value;
                    this.RaisePropertyChanged("PassportNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pincode {
            get {
                return this.PincodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PincodeField, value) != true)) {
                    this.PincodeField = value;
                    this.RaisePropertyChanged("Pincode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyHolderName {
            get {
                return this.PolicyHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyHolderNameField, value) != true)) {
                    this.PolicyHolderNameField = value;
                    this.RaisePropertyChanged("PolicyHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNo {
            get {
                return this.PolicyNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNoField, value) != true)) {
                    this.PolicyNoField = value;
                    this.RaisePropertyChanged("PolicyNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyTypeId {
            get {
                return this.PolicyTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyTypeIdField, value) != true)) {
                    this.PolicyTypeIdField = value;
                    this.RaisePropertyChanged("PolicyTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RationCardNo {
            get {
                return this.RationCardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RationCardNoField, value) != true)) {
                    this.RationCardNoField = value;
                    this.RaisePropertyChanged("RationCardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecieptNo {
            get {
                return this.RecieptNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RecieptNoField, value) != true)) {
                    this.RecieptNoField = value;
                    this.RaisePropertyChanged("RecieptNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesPersonCode {
            get {
                return this.SalesPersonCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesPersonCodeField, value) != true)) {
                    this.SalesPersonCodeField = value;
                    this.RaisePropertyChanged("SalesPersonCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateId {
            get {
                return this.StateIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StateIdField, value) != true)) {
                    this.StateIdField = value;
                    this.RaisePropertyChanged("StateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubTypeId {
            get {
                return this.SubTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTypeIdField, value) != true)) {
                    this.SubTypeIdField = value;
                    this.RaisePropertyChanged("SubTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SudRegion {
            get {
                return this.SudRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.SudRegionField, value) != true)) {
                    this.SudRegionField = value;
                    this.RaisePropertyChanged("SudRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelephoneNo {
            get {
                return this.TelephoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneNoField, value) != true)) {
                    this.TelephoneNoField = value;
                    this.RaisePropertyChanged("TelephoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeOfPortal {
            get {
                return this.TypeOfPortalField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeOfPortalField, value) != true)) {
                    this.TypeOfPortalField = value;
                    this.RaisePropertyChanged("TypeOfPortal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserTypeId {
            get {
                return this.UserTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeIdField, value) != true)) {
                    this.UserTypeIdField = value;
                    this.RaisePropertyChanged("UserTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoterIdNo {
            get {
                return this.VoterIdNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VoterIdNoField, value) != true)) {
                    this.VoterIdNoField = value;
                    this.RaisePropertyChanged("VoterIdNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/SUD.CRM.Portal")]
    [System.SerializableAttribute()]
    public partial class ServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionDetails {
            get {
                return this.ExceptionDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionDetailsField, value) != true)) {
                    this.ExceptionDetailsField = value;
                    this.RaisePropertyChanged("ExceptionDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionReason {
            get {
                return this.ExceptionReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionReasonField, value) != true)) {
                    this.ExceptionReasonField = value;
                    this.RaisePropertyChanged("ExceptionReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestQuery", Namespace="http://schemas.datacontract.org/2004/07/SUD.CRM.Portal")]
    [System.SerializableAttribute()]
    public partial class RequestQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallSubTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNo1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNo2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesPersonCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeverityLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SudRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeOfCallerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeOfPortalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationNo {
            get {
                return this.ApplicationNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNoField, value) != true)) {
                    this.ApplicationNoField = value;
                    this.RaisePropertyChanged("ApplicationNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bank {
            get {
                return this.BankField;
            }
            set {
                if ((object.ReferenceEquals(this.BankField, value) != true)) {
                    this.BankField = value;
                    this.RaisePropertyChanged("Bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallSubType {
            get {
                return this.CallSubTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CallSubTypeField, value) != true)) {
                    this.CallSubTypeField = value;
                    this.RaisePropertyChanged("CallSubType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallType {
            get {
                return this.CallTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CallTypeField, value) != true)) {
                    this.CallTypeField = value;
                    this.RaisePropertyChanged("CallType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNo1 {
            get {
                return this.ContactNo1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNo1Field, value) != true)) {
                    this.ContactNo1Field = value;
                    this.RaisePropertyChanged("ContactNo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNo2 {
            get {
                return this.ContactNo2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNo2Field, value) != true)) {
                    this.ContactNo2Field = value;
                    this.RaisePropertyChanged("ContactNo2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginIdField, value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNo {
            get {
                return this.PolicyNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNoField, value) != true)) {
                    this.PolicyNoField = value;
                    this.RaisePropertyChanged("PolicyNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryType {
            get {
                return this.QueryTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryTypeField, value) != true)) {
                    this.QueryTypeField = value;
                    this.RaisePropertyChanged("QueryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesPersonCode {
            get {
                return this.SalesPersonCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesPersonCodeField, value) != true)) {
                    this.SalesPersonCodeField = value;
                    this.RaisePropertyChanged("SalesPersonCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeverityLevel {
            get {
                return this.SeverityLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.SeverityLevelField, value) != true)) {
                    this.SeverityLevelField = value;
                    this.RaisePropertyChanged("SeverityLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SudRegion {
            get {
                return this.SudRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.SudRegionField, value) != true)) {
                    this.SudRegionField = value;
                    this.RaisePropertyChanged("SudRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeOfCaller {
            get {
                return this.TypeOfCallerField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeOfCallerField, value) != true)) {
                    this.TypeOfCallerField = value;
                    this.RaisePropertyChanged("TypeOfCaller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeOfPortal {
            get {
                return this.TypeOfPortalField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeOfPortalField, value) != true)) {
                    this.TypeOfPortalField = value;
                    this.RaisePropertyChanged("TypeOfPortal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterCaseSummary", Namespace="http://schemas.datacontract.org/2004/07/SUD.CRM.Portal")]
    [System.SerializableAttribute()]
    public partial class FilterCaseSummary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ToDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeofPortalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallID {
            get {
                return this.CallIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CallIDField, value) != true)) {
                    this.CallIDField = value;
                    this.RaisePropertyChanged("CallID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallType {
            get {
                return this.CallTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CallTypeField, value) != true)) {
                    this.CallTypeField = value;
                    this.RaisePropertyChanged("CallType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((this.FromDateField.Equals(value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginIdField, value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNo {
            get {
                return this.PageNoField;
            }
            set {
                if ((this.PageNoField.Equals(value) != true)) {
                    this.PageNoField = value;
                    this.RaisePropertyChanged("PageNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNo {
            get {
                return this.PolicyNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNoField, value) != true)) {
                    this.PolicyNoField = value;
                    this.RaisePropertyChanged("PolicyNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryType {
            get {
                return this.QueryTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryTypeField, value) != true)) {
                    this.QueryTypeField = value;
                    this.RaisePropertyChanged("QueryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ToDate {
            get {
                return this.ToDateField;
            }
            set {
                if ((this.ToDateField.Equals(value) != true)) {
                    this.ToDateField = value;
                    this.RaisePropertyChanged("ToDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeofPortal {
            get {
                return this.TypeofPortalField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeofPortalField, value) != true)) {
                    this.TypeofPortalField = value;
                    this.RaisePropertyChanged("TypeofPortal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseList", Namespace="http://schemas.datacontract.org/2004/07/SUD.CRM.Portal")]
    [System.SerializableAttribute()]
    public partial class CaseList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WIP_Report.CRMCallCreation.CaseDetails[] CaseSummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WIP_Report.CRMCallCreation.CaseDetails[] CaseSummary {
            get {
                return this.CaseSummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseSummaryField, value) != true)) {
                    this.CaseSummaryField = value;
                    this.RaisePropertyChanged("CaseSummary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseDetails", Namespace="http://schemas.datacontract.org/2004/07/SUD.CRM.Portal")]
    [System.SerializableAttribute()]
    public partial class CaseDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallRecieptDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallSubTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChequeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimAmountReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimAmountRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ClaimInimationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PanCardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PincodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RationCardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecieptNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResolutionProvidedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesPersonCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeverityLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SudRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeOfPolicyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeofCallerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoterIdNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address3 {
            get {
                return this.Address3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address3Field, value) != true)) {
                    this.Address3Field = value;
                    this.RaisePropertyChanged("Address3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationNo {
            get {
                return this.ApplicationNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNoField, value) != true)) {
                    this.ApplicationNoField = value;
                    this.RaisePropertyChanged("ApplicationNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOC {
            get {
                return this.BOCField;
            }
            set {
                if ((object.ReferenceEquals(this.BOCField, value) != true)) {
                    this.BOCField = value;
                    this.RaisePropertyChanged("BOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bank {
            get {
                return this.BankField;
            }
            set {
                if ((object.ReferenceEquals(this.BankField, value) != true)) {
                    this.BankField = value;
                    this.RaisePropertyChanged("Bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallRecieptDate {
            get {
                return this.CallRecieptDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CallRecieptDateField, value) != true)) {
                    this.CallRecieptDateField = value;
                    this.RaisePropertyChanged("CallRecieptDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallSubType {
            get {
                return this.CallSubTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CallSubTypeField, value) != true)) {
                    this.CallSubTypeField = value;
                    this.RaisePropertyChanged("CallSubType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallType {
            get {
                return this.CallTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CallTypeField, value) != true)) {
                    this.CallTypeField = value;
                    this.RaisePropertyChanged("CallType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChequeNo {
            get {
                return this.ChequeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChequeNoField, value) != true)) {
                    this.ChequeNoField = value;
                    this.RaisePropertyChanged("ChequeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimAmountReceived {
            get {
                return this.ClaimAmountReceivedField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimAmountReceivedField, value) != true)) {
                    this.ClaimAmountReceivedField = value;
                    this.RaisePropertyChanged("ClaimAmountReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimAmountRequested {
            get {
                return this.ClaimAmountRequestedField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimAmountRequestedField, value) != true)) {
                    this.ClaimAmountRequestedField = value;
                    this.RaisePropertyChanged("ClaimAmountRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ClaimInimationDate {
            get {
                return this.ClaimInimationDateField;
            }
            set {
                if ((this.ClaimInimationDateField.Equals(value) != true)) {
                    this.ClaimInimationDateField = value;
                    this.RaisePropertyChanged("ClaimInimationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimNo {
            get {
                return this.ClaimNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimNoField, value) != true)) {
                    this.ClaimNoField = value;
                    this.RaisePropertyChanged("ClaimNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName {
            get {
                return this.DistrictNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictNameField, value) != true)) {
                    this.DistrictNameField = value;
                    this.RaisePropertyChanged("DistrictName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaxNo {
            get {
                return this.FaxNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNoField, value) != true)) {
                    this.FaxNoField = value;
                    this.RaisePropertyChanged("FaxNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((object.ReferenceEquals(this.FromDateField, value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PanCardNo {
            get {
                return this.PanCardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PanCardNoField, value) != true)) {
                    this.PanCardNoField = value;
                    this.RaisePropertyChanged("PanCardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNo {
            get {
                return this.PassportNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportNoField, value) != true)) {
                    this.PassportNoField = value;
                    this.RaisePropertyChanged("PassportNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pincode {
            get {
                return this.PincodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PincodeField, value) != true)) {
                    this.PincodeField = value;
                    this.RaisePropertyChanged("Pincode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyHolderName {
            get {
                return this.PolicyHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyHolderNameField, value) != true)) {
                    this.PolicyHolderNameField = value;
                    this.RaisePropertyChanged("PolicyHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNo {
            get {
                return this.PolicyNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNoField, value) != true)) {
                    this.PolicyNoField = value;
                    this.RaisePropertyChanged("PolicyNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyTypeId {
            get {
                return this.PolicyTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyTypeIdField, value) != true)) {
                    this.PolicyTypeIdField = value;
                    this.RaisePropertyChanged("PolicyTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryDescription {
            get {
                return this.QueryDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryDescriptionField, value) != true)) {
                    this.QueryDescriptionField = value;
                    this.RaisePropertyChanged("QueryDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryType {
            get {
                return this.QueryTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryTypeField, value) != true)) {
                    this.QueryTypeField = value;
                    this.RaisePropertyChanged("QueryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RationCardNo {
            get {
                return this.RationCardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RationCardNoField, value) != true)) {
                    this.RationCardNoField = value;
                    this.RaisePropertyChanged("RationCardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecieptNo {
            get {
                return this.RecieptNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RecieptNoField, value) != true)) {
                    this.RecieptNoField = value;
                    this.RaisePropertyChanged("RecieptNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestType {
            get {
                return this.RequestTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTypeField, value) != true)) {
                    this.RequestTypeField = value;
                    this.RaisePropertyChanged("RequestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResolutionProvided {
            get {
                return this.ResolutionProvidedField;
            }
            set {
                if ((object.ReferenceEquals(this.ResolutionProvidedField, value) != true)) {
                    this.ResolutionProvidedField = value;
                    this.RaisePropertyChanged("ResolutionProvided");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesPersonCode {
            get {
                return this.SalesPersonCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesPersonCodeField, value) != true)) {
                    this.SalesPersonCodeField = value;
                    this.RaisePropertyChanged("SalesPersonCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeverityLevel {
            get {
                return this.SeverityLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.SeverityLevelField, value) != true)) {
                    this.SeverityLevelField = value;
                    this.RaisePropertyChanged("SeverityLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName {
            get {
                return this.StateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNameField, value) != true)) {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusIDField, value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SudRegion {
            get {
                return this.SudRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.SudRegionField, value) != true)) {
                    this.SudRegionField = value;
                    this.RaisePropertyChanged("SudRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelephoneNo {
            get {
                return this.TelephoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneNoField, value) != true)) {
                    this.TelephoneNoField = value;
                    this.RaisePropertyChanged("TelephoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketNo {
            get {
                return this.TicketNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketNoField, value) != true)) {
                    this.TicketNoField = value;
                    this.RaisePropertyChanged("TicketNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToDate {
            get {
                return this.ToDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ToDateField, value) != true)) {
                    this.ToDateField = value;
                    this.RaisePropertyChanged("ToDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeOfPolicy {
            get {
                return this.TypeOfPolicyField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeOfPolicyField, value) != true)) {
                    this.TypeOfPolicyField = value;
                    this.RaisePropertyChanged("TypeOfPolicy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeofCaller {
            get {
                return this.TypeofCallerField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeofCallerField, value) != true)) {
                    this.TypeofCallerField = value;
                    this.RaisePropertyChanged("TypeofCaller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserTypeId {
            get {
                return this.UserTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeIdField, value) != true)) {
                    this.UserTypeIdField = value;
                    this.RaisePropertyChanged("UserTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoterIdNo {
            get {
                return this.VoterIdNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VoterIdNoField, value) != true)) {
                    this.VoterIdNoField = value;
                    this.RaisePropertyChanged("VoterIdNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRMCallCreation.IFeedback")]
    public interface IFeedback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedback/CreateGrievance", ReplyAction="http://tempuri.org/IFeedback/CreateGrievanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIP_Report.CRMCallCreation.ServiceException), Action="http://tempuri.org/IFeedback/CreateGrievanceServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/SUD.CRM.Portal")]
        string CreateGrievance(WIP_Report.CRMCallCreation.Grievance objCreateGrievance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedback/CreateGrievance", ReplyAction="http://tempuri.org/IFeedback/CreateGrievanceResponse")]
        System.Threading.Tasks.Task<string> CreateGrievanceAsync(WIP_Report.CRMCallCreation.Grievance objCreateGrievance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedback/CreateRequestQuery", ReplyAction="http://tempuri.org/IFeedback/CreateRequestQueryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIP_Report.CRMCallCreation.ServiceException), Action="http://tempuri.org/IFeedback/CreateRequestQueryServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/SUD.CRM.Portal")]
        string CreateRequestQuery(WIP_Report.CRMCallCreation.RequestQuery objCreateRequestQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedback/CreateRequestQuery", ReplyAction="http://tempuri.org/IFeedback/CreateRequestQueryResponse")]
        System.Threading.Tasks.Task<string> CreateRequestQueryAsync(WIP_Report.CRMCallCreation.RequestQuery objCreateRequestQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedback/GetCaseSummary", ReplyAction="http://tempuri.org/IFeedback/GetCaseSummaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIP_Report.CRMCallCreation.ServiceException), Action="http://tempuri.org/IFeedback/GetCaseSummaryServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/SUD.CRM.Portal")]
        WIP_Report.CRMCallCreation.CaseList GetCaseSummary(WIP_Report.CRMCallCreation.FilterCaseSummary ObjFilterCaseSummary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedback/GetCaseSummary", ReplyAction="http://tempuri.org/IFeedback/GetCaseSummaryResponse")]
        System.Threading.Tasks.Task<WIP_Report.CRMCallCreation.CaseList> GetCaseSummaryAsync(WIP_Report.CRMCallCreation.FilterCaseSummary ObjFilterCaseSummary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedback/GetCaseDetails", ReplyAction="http://tempuri.org/IFeedback/GetCaseDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WIP_Report.CRMCallCreation.ServiceException), Action="http://tempuri.org/IFeedback/GetCaseDetailsServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/SUD.CRM.Portal")]
        WIP_Report.CRMCallCreation.CaseDetails GetCaseDetails(string CallID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedback/GetCaseDetails", ReplyAction="http://tempuri.org/IFeedback/GetCaseDetailsResponse")]
        System.Threading.Tasks.Task<WIP_Report.CRMCallCreation.CaseDetails> GetCaseDetailsAsync(string CallID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeedbackChannel : WIP_Report.CRMCallCreation.IFeedback, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeedbackClient : System.ServiceModel.ClientBase<WIP_Report.CRMCallCreation.IFeedback>, WIP_Report.CRMCallCreation.IFeedback {
        
        public FeedbackClient() {
        }
        
        public FeedbackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeedbackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedbackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedbackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateGrievance(WIP_Report.CRMCallCreation.Grievance objCreateGrievance) {
            return base.Channel.CreateGrievance(objCreateGrievance);
        }
        
        public System.Threading.Tasks.Task<string> CreateGrievanceAsync(WIP_Report.CRMCallCreation.Grievance objCreateGrievance) {
            return base.Channel.CreateGrievanceAsync(objCreateGrievance);
        }
        
        public string CreateRequestQuery(WIP_Report.CRMCallCreation.RequestQuery objCreateRequestQuery) {
            return base.Channel.CreateRequestQuery(objCreateRequestQuery);
        }
        
        public System.Threading.Tasks.Task<string> CreateRequestQueryAsync(WIP_Report.CRMCallCreation.RequestQuery objCreateRequestQuery) {
            return base.Channel.CreateRequestQueryAsync(objCreateRequestQuery);
        }
        
        public WIP_Report.CRMCallCreation.CaseList GetCaseSummary(WIP_Report.CRMCallCreation.FilterCaseSummary ObjFilterCaseSummary) {
            return base.Channel.GetCaseSummary(ObjFilterCaseSummary);
        }
        
        public System.Threading.Tasks.Task<WIP_Report.CRMCallCreation.CaseList> GetCaseSummaryAsync(WIP_Report.CRMCallCreation.FilterCaseSummary ObjFilterCaseSummary) {
            return base.Channel.GetCaseSummaryAsync(ObjFilterCaseSummary);
        }
        
        public WIP_Report.CRMCallCreation.CaseDetails GetCaseDetails(string CallID) {
            return base.Channel.GetCaseDetails(CallID);
        }
        
        public System.Threading.Tasks.Task<WIP_Report.CRMCallCreation.CaseDetails> GetCaseDetailsAsync(string CallID) {
            return base.Channel.GetCaseDetailsAsync(CallID);
        }
    }
}
