//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIP_Report.SendOTP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendOTP.IOTP")]
    public interface IOTP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTP/SendMessage", ReplyAction="http://tempuri.org/IOTP/SendMessageResponse")]
        string SendMessage(string ToNumber, string SMSText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOTP/SendMessage", ReplyAction="http://tempuri.org/IOTP/SendMessageResponse")]
        System.Threading.Tasks.Task<string> SendMessageAsync(string ToNumber, string SMSText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOTPChannel : WIP_Report.SendOTP.IOTP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OTPClient : System.ServiceModel.ClientBase<WIP_Report.SendOTP.IOTP>, WIP_Report.SendOTP.IOTP {
        
        public OTPClient() {
        }
        
        public OTPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OTPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OTPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OTPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendMessage(string ToNumber, string SMSText) {
            return base.Channel.SendMessage(ToNumber, SMSText);
        }
        
        public System.Threading.Tasks.Task<string> SendMessageAsync(string ToNumber, string SMSText) {
            return base.Channel.SendMessageAsync(ToNumber, SMSText);
        }
    }
}
